### ISSUE TITLE
Error when compiling MPI enabled version

### ISSUE THREAD

**Issue by koopkaup** [Pbdas/epa-ng#19] opened 2018-11-24 12:59 UTC
Without MPI everything works fine, but when I enable the EPA_HYBRID=1 then I get this error:
```
[ 90%] Building CXX object src/CMakeFiles/epa_module.dir/net/epa_mpi_util.cpp.o
In file included from /gpfs/hpchome/a51256/epa/src/net/epa_mpi_util.cpp:1:0:
/gpfs/hpchome/a51256/epa/src/net/epa_mpi_util.hpp: In function ‘void epa_mpi_send(T&, int, MPI_Comm)’:
/gpfs/hpchome/a51256/epa/src/net/epa_mpi_util.hpp:110:58: error: there are no arguments to ‘memcpy’ that depend on a template parameter, so a declaration of ‘memcpy’ must be available [-fpermissive]
   memcpy(buffer, data.c_str(), data.size() * sizeof(char));
                                                          ^
/gpfs/hpchome/a51256/epa/src/net/epa_mpi_util.hpp:110:58: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/gpfs/hpchome/a51256/epa/src/net/epa_mpi_util.hpp: In function ‘void epa_mpi_isend(T&, int, MPI_Comm, request_tuple&, Timer<>&)’:
/gpfs/hpchome/a51256/epa/src/net/epa_mpi_util.hpp:148:58: error: there are no arguments to ‘memcpy’ that depend on a template parameter, so a declaration of ‘memcpy’ must be available [-fpermissive]
   memcpy(buffer, data.c_str(), data.size() * sizeof(char));
                                                          ^
make[3]: *** [src/CMakeFiles/epa_module.dir/net/epa_mpi_util.cpp.o] Error 1
```

Loaded modules: 
openmpi-4.0.0
cmake/3.8.2
gcc-5.2.0

**Comment by Pbdas** [comment] 2018-11-27 13:38
Thank you for reporting this issue!
While I couldn't reproduce the problem myself, I believe I've fixed it in the dev branch. Could you try to compile that branch and confirm that the issue is resolved?

Thank you,
Pierre

**Comment by Pbdas** [comment] 2018-11-27 14:31
Can you post the exact command line call? Looks like you didn't properly specify the model parameters. Try to get them from your reference tree, or of you don't have them you can re-infer them using RAxML with the `-f e` option, or using the new raxml-ng with the `--evaluate` option.

RAxML will cretae a `.info` file, which you can directly pass to epa-ng's `--model` option.

**Comment by Pbdas** [comment] 2018-11-27 14:38
see also here: https://github.com/Pbdas/epa-ng#setting-the-model-parameters

**Comment by koopkaup** [comment] 2018-11-27 15:31
I used this method to create my reference tree https://www.polarmicrobes.org/phylogenetic-placement-re-re-visited/
And so I used the .info file from building the reference tree. But now I re-created it with `-f e` option and the problem is gone. However, my query sequences were not aligned and caused another error. Can you recommend a MSA aligner with multiprocessor support?

**Comment by lczech** [comment] 2018-11-27 15:39
If you want to be thorough, you can try our PaPaRa aligner, which was specifically developed with phylogenetic placement in mind: https://sco.h-its.org/exelixis/web/software/papara/index.html

It uses the reference tree as an additional source of information, and hence yields better alignments for this use case, as shown in https://doi.org/10.1093/bioinformatics/btr320 as well as http://sco.h-its.org/exelixis/pubs/Exelixis-RRDR-2012-5.pdf

Also, I created a simple MPI version of PaPara: https://github.com/lczech/papara_nt

**Comment by Pbdas** [comment] 2018-11-27 15:50
papara works well, I reccommend it.

See also here for a full example of using placement: https://github.com/Pbdas/epa-ng/wiki/Full-Stack-Example

**Comment by koopkaup** [comment] 2018-11-27 19:49
Thanks, I will try that. But two questions.
Papara only accepts reference alignment in phylip format, however I cannot convert my reference MSA from fasta to phylip, as my fasta headers are longer than 10 characters and cannot be truncated. Is it possible to use MSA in fasta format for Papara?

And the other question comes from your tutorial. 
`
Papara, for example, outputs the aligned queries together with the reference MSA, in phylip format.
(there will be a convenience function for this shortly)
`
How do you separate queries after aligning against reference MSA?

Thank you for the help!

**Comment by lczech** [comment] 2018-11-27 22:15
Yes, this is a downside of PaPaRa - it has tob be phylip for reference and fasta for queries, nothing else works. We are currently starting with a project that will improve PaPaRa, and one of the first things I'll suggest is to allow for more flexible file formats.

Luckily for you, PaPaRa already supports *relaxed* Phylip, with headers as long as they need to be, and which are instead separated from the sequences by (at least one) space. See here for a converter: https://github.com/npchar/Phylogenomic/blob/master/fasta2relaxedPhylip.pl

**Comment by koopkaup** [comment] 2018-11-28 08:38
I had this fatal error in Papara. I assume that there's something fishy with my reference sequences?
`
papara: papara.cpp:538: papara::references<pvec_t, seq_tag>::references(const char*, const char*, papara::queries<seq_tag>*) [with pvec_t = pvec_pgap; seq_tag = sequence_model::tag_dna]: Assertion `unmasked.size() == seq.size()' failed.
`

**Comment by Pbdas** [comment] 2018-11-28 10:13
The convenience function already exists and is called `--split`. I will update the tutorial accordingly. The basic usage is: ```epa-ng --split ref_alignment query_alignments+```

I'm closing this issue as the original bug has been fixed, but we would be happy to help you further on the placement google group (where any errors and solutions become much easier to search for for future users): https://groups.google.com/forum/#!forum/phylogenetic-placement

**Closed by Pbdas** 2018-11-28 10:13 UTC
Labels: bug

**Comment by lczech** [comment] 2018-11-28 10:42
Re fatal error: Please post this again to our forum that @Pbdas mentioned, and maybe add the first few lines of your alignment.
